#!/usr/bin/env bash
# =============================================================================
# Purpose: Define configurable paths, dataset settings, and processing parameters.
# Associated manuscript:
# "A reproducible workflow for high-throughput pyrolysis gas
# chromatography–mass spectrometry analysis of soil organic matter".
# Usage, inputs, outputs, and parameters: see README.md.
# =============================================================================

# Processing settings. Exported environment values override these defaults.

_PIPELINE_CONFIG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${PROJECT_DIR:-$(cd "${_PIPELINE_CONFIG_DIR}/../.." && pwd)}"
export PROJECT_DIR
PYTHON_BIN="${PYTHON_BIN:-python3}"
DATASET_ID="${DATASET_ID:-case2_alignment}"
RUN_ROOT="${RUN_ROOT:-${PROJECT_DIR}/pygcms_method_outputs}"

SOURCE_DATASET_ID="${SOURCE_DATASET_ID_OVERRIDE:-${DATASET_ID}}"
SOURCE_DATASET_ID="${SOURCE_DATASET_ID%_alignment}"

# Input data are derived from DATASET_ID to avoid stale exported CDF_DIR values.
# For non-standard input folders, set CDF_DIR_OVERRIDE explicitly.
CDF_DIR="${CDF_DIR_OVERRIDE:-${PROJECT_DIR}/${SOURCE_DATASET_ID} spectrum}"

# These paths are derived from DATASET_ID on every run. Do not let stale
# exported RUN_DIR/WORK_DIR/MAIN_OUTPUT_DIR values send a new dataset into an
# old output folder.
RUN_DIR="${RUN_ROOT}/${DATASET_ID}"
WORK_DIR="${RUN_DIR}/work_files"
MAIN_OUTPUT_DIR="${RUN_DIR}/main_outputs"

# Peak detection and filtering
MIN_PEAK_HEIGHT="${MIN_PEAK_HEIGHT:-8000}"
MIN_PEAK_WIDTH="${MIN_PEAK_WIDTH:-2.5}"
NOISE_THRESHOLD="${NOISE_THRESHOLD:-1000}"
ANALYSIS_START_MIN="${ANALYSIS_START_MIN:-3}"
ANALYSIS_END_MIN="${ANALYSIS_END_MIN:-90}"

AREA_FRACTION_FILTER="${AREA_FRACTION_FILTER:-0.005}"

FOUNDIN_MIN="${FOUNDIN_MIN:-3}"
COMPOUND_ID_PREFIX="${COMPOUND_ID_PREFIX:-C}"
COMPOUND_ID_DIGITS="${COMPOUND_ID_DIGITS:-3}"

# Manual review and compound merging
POST_REVIEW_MERGE_RT_SEC="${POST_REVIEW_MERGE_RT_SEC:-60}"
POST_REVIEW_UNIDENTIFIED_COSINE="${POST_REVIEW_UNIDENTIFIED_COSINE:-0.90}"
POST_REVIEW_UNIDENTIFIED_MAX_JACCARD="${POST_REVIEW_UNIDENTIFIED_MAX_JACCARD:-0.10}"

# Spectral libraries and candidate search
MONA_FILE="${MONA_FILE:-${PROJECT_DIR}/MoNA-export-GC-MS_Spectra_with_internal_standards.msp}"
NIST_FILES_DEFAULT="${PROJECT_DIR}/NIST 2020 export/mainlib_part01.MSP;${PROJECT_DIR}/NIST 2020 export/mainlib_part02.MSP;${PROJECT_DIR}/NIST 2020 export/mainlib_part03.MSP;${PROJECT_DIR}/NIST 2020 export/mainlib_part04.MSP;${PROJECT_DIR}/NIST 2020 export/mainlib_part05.MSP;${PROJECT_DIR}/NIST 2020 export/relib_MIST.MSP"
NIST_FILES="${NIST_FILES:-${NIST_FILE:-${NIST_FILES_DEFAULT}}}"
# Backward-compatible single-path value for older helper scripts.
NIST_FILE="${NIST_FILE:-${PROJECT_DIR}/NIST 2020 export/mainlib_part01.MSP}"

TOP_HITS_PER_LIBRARY="${TOP_HITS_PER_LIBRARY:-20}"
PRIMARY_TOP_HITS_PER_LIBRARY="${PRIMARY_TOP_HITS_PER_LIBRARY:-5}"
RESCUE_TOP_HITS_PER_LIBRARY="${RESCUE_TOP_HITS_PER_LIBRARY:-20}"
PUBCHEM_DELAY_SEC="${PUBCHEM_DELAY_SEC:-0.12}"
PUBCHEM_TIMEOUT_SEC="${PUBCHEM_TIMEOUT_SEC:-8}"

# RI-guided annotation. Every Top-N hit is retained; match score is never a
# hard deletion threshold. Comparable reference values are restricted to
# temperature-programmed DB-5-type stationary phases.
ALKANE_RI_FILE="${ALKANE_RI_FILE:-${PROJECT_DIR}/alkane_RI.csv}"
REFERENCE_RI_OUTPUT_DIR="${REFERENCE_RI_OUTPUT_DIR:-${WORK_DIR}/05_reference_ri_mapping}"
export REFERENCE_RI_OUTPUT_DIR
REFERENCE_RI_INTERNAL_STANDARD_RT_FILE="${REFERENCE_RI_INTERNAL_STANDARD_RT_FILE:-${PROJECT_DIR}/reference_internal_standard_rts.csv}"
REFERENCE_RI_EXPECTED_BLOCK="${REFERENCE_RI_EXPECTED_BLOCK:-}"
SOM_REFERENCE_FILE="${SOM_REFERENCE_FILE:-${PROJECT_DIR}/SOM_PyGCMS_EI_pipeline_reference_library_v1.0.xlsx}"
RI_CACHE_DIR="${RI_CACHE_DIR:-${RUN_ROOT}/shared_cache/nist_webbook_db5_ri}"
RI_SUPPORT_WINDOW="${RI_SUPPORT_WINDOW:-20}"
RI_WEAK_WINDOW="${RI_WEAK_WINDOW:-50}"
SPECTRAL_AUTO_THRESHOLD="${SPECTRAL_AUTO_THRESHOLD:-850}"
ANNOTATION_DECISION_POLICY="${ANNOTATION_DECISION_POLICY:-two_stage_top20_rescue}"
ANNOTATION_RECOMPUTE_FROM_CACHE="${ANNOTATION_RECOMPUTE_FROM_CACHE:-false}"
RI_QUERY_TIMEOUT_SEC="${RI_QUERY_TIMEOUT_SEC:-20}"
RI_QUERY_DELAY_SEC="${RI_QUERY_DELAY_SEC:-0.12}"
RI_OFFLINE="${RI_OFFLINE:-false}"
PUBCHEM_IDENTITY_CACHE_DIR="${PUBCHEM_IDENTITY_CACHE_DIR:-${RUN_ROOT}/shared_cache/pubchem_identity}"
PUBCHEM_QUERY_TIMEOUT_SEC="${PUBCHEM_QUERY_TIMEOUT_SEC:-20}"
PUBCHEM_QUERY_DELAY_SEC="${PUBCHEM_QUERY_DELAY_SEC:-0.12}"
PUBCHEM_OFFLINE="${PUBCHEM_OFFLINE:-${RI_OFFLINE}}"

# Sample grouping and peak alignment
ALIGNMENT_MODE="${ALIGNMENT_MODE:-auto}"  # auto, single, or blockwise
ALIGNMENT_SINGLE_BLOCK_THRESHOLD="${ALIGNMENT_SINGLE_BLOCK_THRESHOLD:-25}"
ALIGNMENT_DIR="${ALIGNMENT_DIR:-${WORK_DIR}/04_alignment}"
ALIGNMENT_PREBLOCK_DIR="${ALIGNMENT_PREBLOCK_DIR:-${WORK_DIR}/03_alignment_preblock}"
ALIGNMENT_ALIGN_TIME_DIST="${ALIGNMENT_ALIGN_TIME_DIST:-60}"
ALIGNMENT_SINGLE_BLOCK_TIME_DIST_SEC="${ALIGNMENT_SINGLE_BLOCK_TIME_DIST_SEC:-60}"
ALIGNMENT_MIN_BLOCK_SIZE="${ALIGNMENT_MIN_BLOCK_SIZE:-10}"
ALIGNMENT_MAX_BLOCK_SIZE="${ALIGNMENT_MAX_BLOCK_SIZE:-25}"
ALIGNMENT_TARGET_MAX_TIME_DIST="${ALIGNMENT_TARGET_MAX_TIME_DIST:-30}"
ALIGNMENT_USE_EXISTING_PREBLOCK="${ALIGNMENT_USE_EXISTING_PREBLOCK:-false}"
ALIGNMENT_USE_EXISTING_BLOCK_FOLDERS="${ALIGNMENT_USE_EXISTING_BLOCK_FOLDERS:-false}"

ALIGNMENT_MIN_SPECTRA_COR="${ALIGNMENT_MIN_SPECTRA_COR:-0.90}"
ALIGNMENT_MZ_MIN="${ALIGNMENT_MZ_MIN:-46}"
ALIGNMENT_MZ_MAX="${ALIGNMENT_MZ_MAX:-650}"
ALIGNMENT_AVOID_PROCESSING_MZ="${ALIGNMENT_AVOID_PROCESSING_MZ:-74:75,147:149,207,281}"
ALIGNMENT_POST_CONSOLIDATION="${ALIGNMENT_POST_CONSOLIDATION:-true}"
ALIGNMENT_FINAL_FEATURE_MERGE_RT_SEC="${ALIGNMENT_FINAL_FEATURE_MERGE_RT_SEC:-60}"
ALIGNMENT_FINAL_FEATURE_MERGE_SPECTRAL_COS="${ALIGNMENT_FINAL_FEATURE_MERGE_SPECTRAL_COS:-0.90}"
ALIGNMENT_FINAL_FEATURE_MERGE_BASE_MZ_TOL="${ALIGNMENT_FINAL_FEATURE_MERGE_BASE_MZ_TOL:-1}"

# AlignID=0 peaks remain first-class block features. These conservative rules
# are shared by within-block repair and second-pass cross-block merging.
ALIGNID0_RESCUE_ENABLED="${ALIGNID0_RESCUE_ENABLED:-true}"
ALIGNID0_WITHIN_BLOCK_RT_SEC="${ALIGNID0_WITHIN_BLOCK_RT_SEC:-60}"
ALIGNID0_MIN_SPECTRAL_COSINE="${ALIGNID0_MIN_SPECTRAL_COSINE:-0.90}"
ALIGNID0_BASE_MZ_TOL="${ALIGNID0_BASE_MZ_TOL:-1}"
ALIGNID0_AMBIGUITY_MARGIN="${ALIGNID0_AMBIGUITY_MARGIN:-0.01}"

ALIGNMENT_GLOBAL_MERGE_RT_SEC="${ALIGNMENT_GLOBAL_MERGE_RT_SEC:-60}"
ALIGNMENT_GLOBAL_MERGE_SPECTRAL_COS="${ALIGNMENT_GLOBAL_MERGE_SPECTRAL_COS:-0.90}"
ALIGNMENT_GLOBAL_MERGE_BASE_MZ_TOL="${ALIGNMENT_GLOBAL_MERGE_BASE_MZ_TOL:-1}"
ALIGNMENT_RT_CORRECTION_METHOD="${ALIGNMENT_RT_CORRECTION_METHOD:-adaptive_landmark}"
ALIGNMENT_LANDMARK_IDENTITY_MEDIAN_SEC="${ALIGNMENT_LANDMARK_IDENTITY_MEDIAN_SEC:-5}"
ALIGNMENT_LANDMARK_IDENTITY_MAX_SEC="${ALIGNMENT_LANDMARK_IDENTITY_MAX_SEC:-15}"
ALIGNMENT_LATE_ANCHOR_START_MIN="${ALIGNMENT_LATE_ANCHOR_START_MIN:-30}"
ALIGNMENT_LATE_ANCHOR_FULL_MIN="${ALIGNMENT_LATE_ANCHOR_FULL_MIN:-45}"
ALIGNMENT_LATE_ANCHOR_WARN_SEC="${ALIGNMENT_LATE_ANCHOR_WARN_SEC:-15}"
ALIGNMENT_LATE_ANCHOR_BLOCK_SEC="${ALIGNMENT_LATE_ANCHOR_BLOCK_SEC:-30}"
